rssLimit: 20
baseURL: "Occupation-Genome-Project.github.io"
title: Occupation-Genome-Project
theme: my-hugo-theme
disablePathToLower: true
publishDir: docs
languageCode: en-us

params:
  selected_item_list: "Occupation-Genome-Project:Occupation-Genome-Project;"

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  publishDate:
    - publishDate
    - date
  lastMod:
    - lastMod
    - publishDate
    - date

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  defaultMarkdownHandler: goldmark
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 1
